# config.yaml
# Analysis_Th v4.2 · v5.2 공통 설정 파일
# ----------------------------------------------------------
# weighting_scheme 값의 합은 1.0이어야 하며, 0–1 실수로 입력한다.
# methodology_override는 Phase 0 자동 추천을 덮어쓸 때만 지정한다.
# override_gate를 true로 두면 Phase 2.5에서 ‘미흡/취약’ 등급이어도
# 워크플로우가 중단되지 않고 Phase 3·4로 계속 진행된다.
# ----------------------------------------------------------

weighting_scheme:
  frequency:          0.40   # 텍스트 표면 빈도
  network_centrality: 0.35   # 개념 네트워크 중심성
  citation_count:     0.25   # 외부 인용 빈도

methodology_override:
  # Phase 0 결과 대신 강제로 적용할 주·보조 방법론을 지정한다.
  # 값을 비워 두면 Phase 0의 recommended_methodology를 따른다.
  primary:   ""              # 예) "서사적 해석"
  auxiliary: []              # 예) ["실천신학적 검토"]

override_gate: false         # true: 품질 게이트 무시, false: 차단 유지

# ----------------------------------------------------------
# 추가 설정
model_name: "gemini-2.5-pro" # 사용할 Gemini 모델 이름
