# config.yaml
# Analysis_Th v1.1 공통 설정 파일

# ==========================================================
# 1. 프로젝트 전역 설정 (Global Settings)
# 이 설정들은 워크플로우 전체의 동작 방식을 제어합니다.
# ==========================================================
project_settings:
  # manual: 모든 Phase 후 승인 | auto: 자동 통과 | conditional: 아래 rules 따름
  approval_mode: "conditional"
  conditional_rules:
    - phase_id: "0"
      require_user: true
  
  # LLM 모델 및 API 관련
  model_name: "gemini-1.5-pro-latest"
  max_retries: 3
  
  # 실행 제어
  timeout_seconds: 3600
  logging_level: "INFO" # DEBUG, INFO, WARNING, ERROR

# ==========================================================
# 2. 분석 파라미터 (Analysis Parameters)
# 이 설정들은 분석의 내용과 깊이에 영향을 줍니다.
# ==========================================================
analysis_parameters:
  # weighting_scheme 값의 합은 1.0이어야 합니다.
  weighting_scheme:
    frequency:          0.40   # 텍스트 표면 빈도
    network_centrality: 0.35   # 개념 네트워크 중심성
    citation_count:     0.25   # 외부 인용 빈도

  # Phase 0 결과 대신 강제로 적용할 방법론을 지정합니다.
  methodology_override:
    primary:   ""              # 예) "서사적 해석"
    auxiliary: []              # 예) ["실천신학적 검토"]

  # Phase 2.5 품질 게이트를 무시할지 여부
  override_gate: false
